### PR TITLE
Push remind local changes upstream

### PR DESCRIPTION
**Pull request by danilotsr**
Why not return the e164 prefix which matches as part of the lookup return value? It seems pretty useful to me in order to avoid duplicating that logic on the caller side in case one needs to know the prefix part of a phone number.

@dalyons

### CODE REVIEW

**Comment by pdeschen** [comment]
Yeah that seems legit. Would you mind re-opening your PR? I'd integrate you changes as well

**Comment by pdeschen** [comment]
Nevermind: found that re-open PR butot :-)

**Comment by danilotsr** [comment]
@pdeschen this PR was actually a mistake on my part as I intended to open it against our own fork of this lib (remind101/e164.js). Not sure why we haven't been merging our local changes upstream, maybe @dalyons would have more context.

**Comment by danilotsr** [comment]
@pdeschen ok, I'm done with the local changes now, let me know if you want me to go ahead and merge this upstream.

**Comment by danilotsr** [comment]
It's been over a year, so I'm going to just abandon this.

**Pull request closed without merging**
